name: suma-ic

on:
  pull_request:
    branches: main
  
jobs:
  ci-to-master:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          npm install jest
          npm test
          npm run build
  cd:
    needs: ci-to-master
    runs-on: ubuntu-latest

    steps:
      - name: validation-for-pdn
        env:
          eventname: ${{ github.event_name }}

        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "deploy to pdn"
      - name: Publish with Verdaccio
        uses: verdaccio/github-actions/publish@master
