name: suma-ic

on:
  pull_request:
    branches: main
  
jobs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: verdaccio/github-actions/canary@master
      with:
        message: 'Thanks for your PR, we have promoted your PR and created a canary version of your proposal:'
        is-global: true
        package-name: '@verdaccio/ui-theme'
        registry: 'https://registry.verdaccio.org'
        bot-token: ${{ secrets.VERDACCIO_BOT_TOKEN }}
        bot-name: verdacciobot
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.verdaccio.org'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}
