name: suma-ic

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checks out code
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies using a safe clean install
      run: |
        npm ci --ignore-scripts
        ls
        echo ${{secrets.NPM_TOKEN}}
        nano .npmrc
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        
# skip 'registry-url' and 'always-auth: true' parameters if these are provided by a custom .npmrc file
