name: suma-ic

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checks out code
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        always-auth: true
        node-version: '14.x'
        registry-url: https://npm.leal.co/
    - name: Publish dependencies on Verdaccio
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.VERDACCIO_TOKEN}}
